### ISSUE TITLE
Exception when no spots are found

### ISSUE THREAD

**Issue by tpietzsch** [TrNdy/mastodon-tracking#2]
When setting detection parameters such that no spots are found:

```
Exception in thread "DogDetectorPanel preview thread" java.lang.ArrayIndexOutOfBoundsException: -1
	at net.imglib2.util.Partition.partitionSubList(Partition.java:406)
	at net.imglib2.util.KthElement.kthElement(KthElement.java:312)
	at net.imglib2.util.KthElement.kthElement(KthElement.java:340)
	at net.imglib2.util.Util.percentile(Util.java:164)
	at org.mastodon.trackmate.ui.wizard.util.HistogramUtil.getNBins(HistogramUtil.java:95)
	at org.mastodon.trackmate.ui.wizard.util.HistogramUtil.createHistogramPlot(HistogramUtil.java:27)
	at org.mastodon.trackmate.ui.wizard.descriptors.DogDetectorDescriptor.plotQualityHistogram(DogDetectorDescriptor.java:270)
	at org.mastodon.trackmate.ui.wizard.descriptors.DogDetectorDescriptor.access$600(DogDetectorDescriptor.java:69)
	at org.mastodon.trackmate.ui.wizard.descriptors.DogDetectorDescriptor$1.run(DogDetectorDescriptor.java:252)
```

**Comment by tinevez** [comment]
Fixed with 48c3d44c22ceaa399d2d709a78e5c587c00b8004
